[theme]
base="dark"
primaryColor="#F63366"  # A vibrant pink-red, for contrast and emphasis
backgroundColor="#262730"  # A dark blue-gray, similar to Streamlit's default dark mode
secondaryBackgroundColor="#0E1117"  # A very dark blue-gray, almost black
